apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "relayforge.fullname" . }}-helm-test
  labels:
    {{- include "relayforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: helm-test
automountServiceAccountToken: false