apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relayforge.fullname" . }}-destinations
  labels:
    {{- include "relayforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  destinations.json: {{ .Values.destinations | toJson | quote }}